version: '3'
services:
  mock-server:
    image: node:lts-alpine
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ..:/srv
      - logvolume01:/var/log
    entrypoint: npm run --prefix /srv start:mock
volumes:
  logvolume01: {}
